name: Run Operator SDK tests, release new operator images if tests succeed

on:
  schedule:
    - cron: '0 1 * * *' # everyday at 1am
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          config: molecule/kind-cluster/files/kind-config.yml
          name: osdk-test
          version: v0.9.0
      - name: Prereq setup
        run: develop/ci-setup.sh
      - name: Test
        run: develop/ci-test.sh kind-cluster

  test-namespace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          config: molecule/kind-cluster/files/kind-config.yml
          name: osdk-test
          version: v0.9.0
      - name: Prereq setup
        run: develop/ci-setup.sh
      - name: Test
        run: develop/ci-test.sh kind-namespace

  release:
    needs: [test-cluster, test-namespace]
    if: >
      github.event_name != 'pull_request' &&
      (github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Login to Quay
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Install pip pre-reqs
        run: pip3 install --user --upgrade setuptools wheel pip

      - name: Generate bundle
        run: develop/operate.sh --bundle-generate --extra-tag=latest --verbose --formatter

      - name: Process bundle for disconnected support
        uses: adamgoossens/github-actions/disconnected-csv@main
        with:
          CSV_FILE: bundle/manifests/nexus-operator.clusterserviceversion.yaml
          TAGS_TO_DIGESTS: 1

      - name: Build and push operator image
        run: develop/operate.sh --push-images --push-only --extra-tag=latest --verbose --formatter --img ${{secrets.IMAGE_REPOSITORY}}

      - name: Build and push bundle image
        run: develop/operate.sh --bundle-publish --verbose --formatter --extra-tag=latest -- img ${{secrets.IMAGE_REPOSITORY}}
